version: '3.1'

services:

  redmine:
    image: redmine:4.1.0
    restart: always
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
    volumes:
      - ./:/usr/src/redmine/plugins/redspot

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
    volumes:
      - db-storage:/var/lib/mysql

volumes:
  db-storage: ~
